  .model small 
  .386
  .stack 256  
   .data
RAX1 DW 1234H
RBX1 DW ?
RCX1 DW 0FFFFH
RDX1 DW 0EFCBH
ISI1 DW 4371H 
IDI1 DW 5678H
SSP1 DW ?
BBP1 DW ?
COM1 DB 13,11,'m','o','v',' ','a','x',',','1','f','f','f'
COMp1  DB 'm','o','v',' ','a','x',',','1','f','f','f'
MEMORY DB 100 DUP(?)
;ARRAY OF NUMBERS IN HEXA
NUM_HEXA DB '0','1','2','3','4','5','6','7','8','9','A','B','C','D','E','F'

;;NUMBER TO DISPLAY IN REGISTERS
NUMTODISP DB 4 DUP(?) 
A_SIZE1 db ?

.CODE 
INCLUDE MACROS.INC
INCLUDE COMPINST.INC
INCLUDE COUNTNUM.INC 
INCLUDE PRINTNUM.INC
INCLUDE COMINST2.INC
MAIN PROC FAR  
    MOV AX,@DATA
    MOV DS,AX   

     ;READ_COMMAND COM1+2,A_SIZE1,1
     ;LEA DI,COM1+1
     ;MOV CL,A_SIZE1
     ;MOV [DI],CL
     ;UP_TO_LOW COM1+2, COMp1,COM1+1  


    MOV SI,OFFSET COMp1 
    MOV AX,0
    MOV CX,0
    MOV AL,[SI+4] 
    ADD CL,[SI+5]
    ADD AX,CX   
    
    ;CMP [SI+6],','                          ;LW FEH MEMORY LMODO3 HE5TLF2B2A 5LE CHECK MEMORY 2BL
     JNZ ERROR
    CMP AX,217
    JZ NTAAXDES
    CMP AX,218                   ;BN3ML JUMP 3LA 7BT 7GAT W M7TNA4 MEMORY 4OF B2AA
    JZ NTABXDES
    CMP AX,219                    ;ANAM7TAGFUNCTIONT4OFLE 7WAR 2RKAM KDA KDA HOMA BLKTEER 4 2RKAM 3NDE M4AKL KBEERAA FE 2RKAM 5LE BALK ANA HA5OD 2RKAM MN 3LA 2L4MAAAL YAMEGZ 
    JZ NTACXDES
    CMP AX,220
    JZ NTADXORSIDES
    CMP AX,205
    JZ NTADIORALDES
    CMP AX,201
    JZ NTAAHDIS
    CMP AX,206
    JZ NTABLDIS
    CMP AX,202
    JZ NTABHDIS
    CMP AX,207
    JZ NTACLDIS
    CMP AX,203
    JZ NTACHDIS
    CMP AX,208
    JZ NTADLDIS
    CMP AX,204
    JZ NTADHDIS 
    JMP ERROR
NTAAXDES: 
  MOV CX,0
  MOV AX,0
  MOV AL,[SI+7] 
  MOV CL,[SI+8]
  ADD AX,CX
  CMP AX,217
  JZ NTAAXDESWAXSOURCE
  CMP AX,218 
  JZ NTAAXDESWBXSOURCE
  CMP AX,219
  JZ NTAAXDESWCXSOURCE
  CMP AX,220
 JZ NTAAXDESWDXORSISOURCE
 CMP AX,205
 JZ NTAAXDESWDIORALLWALERROR
 MOV CX,0
 MOV BX,0                            ;TAKECARE
 MOV BL,[SI+9]
 MOV CL,[SI+10]
 ADD CX,BX
 ADD AX,CX
 CMP AX,402
 JZ AXDES_WNTA_MEMBX
 CMP AX,404              
 JZ NTA_AXDES_WMEMSI
 CMP AX,389
 JZ NTA_AXDES_WMEMDI
 JMP NTAAXDESW_RKM_YA_MEMRKM_YAERROR  
 
 NTAAXDESWAXSOURCE:  
 ;ME4H3ML 7AGAA
 JMP NAG7
 
 NTAAXDESWBXSOURCE: 
 MOV BX,RBX1
 MOV RAX1,BX
 JMP NAG7
 NTAAXDESWCXSOURCE:
 MOV BX,RCX1
 MOV RAX1,BX
 JMP NAG7 
 NTAAXDESWDXORSISOURCE:
 MOV AL,[SI+7]
 CMP AL,100
 JZ NTAAXDESWDXSOURCE
  
NTAAXDESWSISOURCE:
MOV BX,ISI1
MOV RAX1,BX
JMP NAG7
NTAAXDESWDXSOURCE:
MOV BX,RDX1
MOV RAX1,BX
JMP NAG7
NTAAXDESWDIORALLWALERROR: 
MOV AL,[SI+7]
CMP AL,100 
JZ NTAAXDESWDISOURCE
JMP ERROR
NTAAXDESWDISOURCE:
MOV BX,IDI1
MOV RAX1,BX
JMP NAG7
AXDES_WNTA_MEMBX:
MOV BX,RBX1
CMP BX,0FH
JA ERROR
MOV AL, MEMORY[BX]
MOV AH, MEMORY[BX+1]
MOV RAX1,AX
JMP NAG7
NTA_AXDES_WMEMSI:
MOV BX,ISI1
CMP BX,0FH
JA ERROR
MOV AH, MEMORY[BX+1]
MOV AL, MEMORY[BX]
MOV RAX1,AX
JMP NAG7
NTA_AXDES_WMEMDI:
MOV BX,IDI1
CMP BX,0FH
JA ERROR
MOV AH, MEMORY[BX+1]
MOV AL, MEMORY[BX]
MOV RAX1,AX
JMP NAG7
NTAAXDESW_RKM_YA_MEMRKM_YAERROR:
MOV AL,[SI+7]
CMP AL,91
JZ MEMRKM_ORERROR_AXDES

RKM_ORERROR_AXDES:
MOV AL,[SI+8]
CMP AL,108
JZ ERROR
CMP AL,104
JZ ERROR

RET_NUM_COUNT  COMp1+7
CMP CX,4
JA ERROR
MOV RAX1,DX
JMP NAG7
MEMRKM_ORERROR_AXDES:
MOV AL,[SI+9]
CMP AL,108
JZ ERROR
CMP AL,104
JZ ERROR
RET_NUM_COUNT  COMp1+8
CMP CX,4
JA ERROR
CMP DX,0FH
JA ERROR
MOV BX,DX
MOV AH, MEMORY[BX+1]
MOV AL, MEMORY[BX]
MOV RAX1,AX
JMP NAG7
;/////////////////////////////////////////////////////////////////////////////////////////////////////////////
NTABXDES:
  MOV CX,0
  MOV AX,0
  MOV AL,[SI+7] 
  MOV CL,[SI+8]
  ADD AX,CX
  CMP AX,217
  JZ NTABXDESWAXSOURCE
  CMP AX,218 
  JZ NTABXDESWBXSOURCE
  CMP AX,219
  JZ NTABXDESWCXSOURCE
  CMP AX,220
 JZ NTABXDESWDXORSISOURCE
 CMP AX,205
 JZ NTABXDESWDIORALLWALERROR
 MOV BX,0
 MOV CX,0                              ;TAKECARE
 MOV CL,[SI+9]
 MOV BL,[SI+10]
 ADD CX,BX
 ADD AX,CX
 CMP AX,402
 JZ BXDES_WNTA_MEMBX
 CMP AX,404              
 JZ NTA_BXDES_WMEMSI
 CMP AX,389
 JZ NTA_BXDES_WMEMDI
 JMP NTABXDESW_RKM_YA_MEMRKM_YAERROR  
 
 NTABXDESWAXSOURCE:  
 MOV AX,RAX1
 MOV RBX1,AX
 JMP NAG7
 
 NTABXDESWBXSOURCE: 
 JMP NAG7
 NTABXDESWCXSOURCE:
 MOV BX,RCX1
 MOV RBX1,BX
 JMP NAG7 
 NTABXDESWDXORSISOURCE:
 MOV AL,[SI+7]
 CMP AL,100
 JZ NTABXDESWDXSOURCE
  
NTABXDESWSISOURCE:
MOV BX,ISI1
MOV RBX1,BX
JMP NAG7
NTABXDESWDXSOURCE:
MOV BX,RDX1
MOV RBX1,BX
JMP NAG7
NTABXDESWDIORALLWALERROR: 
MOV AL,[SI+7]
CMP AL,100 
JZ NTABXDESWDISOURCE
JMP ERROR
NTABXDESWDISOURCE:
MOV BX,IDI1
MOV RBX1,BX
JMP NAG7
BXDES_WNTA_MEMBX:
MOV BX,RBX1
CMP BX,0FH
JA ERROR
MOV AH, MEMORY[BX+1]
MOV AL, MEMORY[BX]
MOV RBX1,AX
JMP NAG7
 NTA_BXDES_WMEMSI:
MOV BX,ISI1
CMP BX,0FH
JA ERROR
MOV AH, MEMORY[BX+1]
MOV AL, MEMORY[BX]
MOV RBX1,AX
JMP NAG7
NTA_BXDES_WMEMDI:
MOV BX,IDI1
CMP BX,0FH
JA ERROR
MOV AH, MEMORY[BX+1]
MOV AL, MEMORY[BX]
MOV RBX1,AX
JMP NAG7
NTABXDESW_RKM_YA_MEMRKM_YAERROR:
MOV AL,[SI+7]
CMP AL,91
JZ MEMRKM_ORERROR_BXDES

RKM_ORERROR_BXDES:
MOV AL,[SI+8]
CMP AL,108
JZ ERROR
CMP AL,104
JZ ERROR
RET_NUM_COUNT  COMp1+7
CMP CX,4
JA ERROR
MOV RBX1,DX
JMP NAG7
MEMRKM_ORERROR_BXDES:
MOV AL,[SI+9]
CMP AL,108
JZ ERROR
CMP AL,104
JZ ERROR
RET_NUM_COUNT  COMp1+8
CMP CX,4
JA ERROR
CMP DX,0FH
JA ERROR
MOV BX,DX
MOV AH, MEMORY[BX+1]
MOV AL, MEMORY[BX]
MOV RBX1,AX
JMP NAG7
;/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
NTACXDES:
 MOV CX,0
 MOV AX,0
 MOV AL,[SI+7] 
 MOV CL,[SI+8]
 ADD AX,CX
 CMP AX,217
 JZ NTACXDESWAXSOURCE
 CMP AX,218 
 JZ NTACXDESWBXSOURCE
 CMP AX,219
 JZ NTACXDESWCXSOURCE
 CMP AX,220
 JZ NTACXDESWDXORSISOURCE
 CMP AX,205
 JZ NTACXDESWDIORALLWALERROR 
 
 MOV BX,0
 MOV CX,0                              ;TAKECARE
 MOV CL,[SI+9]
 MOV BL,[SI+10]
 ADD CX,BX
 ADD AX,CX
 CMP AX,402
 JZ CXDES_WNTA_MEMBX
 CMP AX,404              
 JZ NTA_CXDES_WMEMSI
 CMP AX,389
 JZ NTA_CXDES_WMEMDI
 JMP NTACXDESW_RKM_YA_MEMRKM_YAERROR  
 
 NTACXDESWAXSOURCE:  
 MOV AX,RAX1
 MOV RCX1,AX
 JMP NAG7
 
 NTACXDESWBXSOURCE: 
 MOV AX,RBX1
 MOV RCX1,AX
 JMP NAG7
 NTACXDESWCXSOURCE:
 JMP NAG7 
 NTACXDESWDXORSISOURCE:
 MOV AL,[SI+7]
 CMP AL,100
 JZ NTACXDESWDXSOURCE
  
NTACXDESWSISOURCE:
MOV BX,ISI1
MOV RCX1,BX
JMP NAG7
NTACXDESWDXSOURCE:
MOV BX,RDX1
MOV RCX1,BX
JMP NAG7
NTACXDESWDIORALLWALERROR: 
MOV AL,[SI+7]
CMP AL,100 
JZ NTACXDESWDISOURCE
JMP ERROR
NTACXDESWDISOURCE:
MOV BX,IDI1
MOV RCX1,BX
JMP NAG7
CXDES_WNTA_MEMBX:
MOV BX,RBX1
CMP BX,0FH
JA ERROR
MOV AH, MEMORY[BX+1]
MOV AL, MEMORY[BX]
MOV RCX1,AX
JMP NAG7
 NTA_CXDES_WMEMSI:
MOV BX,ISI1
CMP BX,0FH
JA ERROR
MOV AH, MEMORY[BX+1]
MOV AL, MEMORY[BX]
MOV RCX1,AX
JMP NAG7
NTA_CXDES_WMEMDI:
MOV BX,IDI1
CMP BX,0FH
JA ERROR
MOV AH, MEMORY[BX+1]
MOV AL, MEMORY[BX]
MOV RCX1,AX
JMP NAG7
NTACXDESW_RKM_YA_MEMRKM_YAERROR:
MOV AL,[SI+7]
CMP AL,91
JZ MEMRKM_ORERROR_CXDES

RKM_ORERROR_CXDES:
MOV AL,[SI+8]
CMP AL,108
JZ ERROR
CMP AL,104
JZ ERROR
RET_NUM_COUNT  COMp1+7
CMP CX,4
JA ERROR
MOV RCX1,DX
JMP NAG7
MEMRKM_ORERROR_CXDES:
MOV AL,[SI+9]
CMP AL,108
JZ ERROR
CMP AL,104
JZ ERROR
RET_NUM_COUNT  COMp1+8
CMP CX,4
JA ERROR
CMP DX,0FH
JA ERROR
MOV BX,DX
MOV AH, MEMORY[BX+1]
MOV AL, MEMORY[BX]
MOV RCX1,AX
JMP NAG7
;//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
NTADXORSIDES:
MOV AL,[SI+4]
CMP AL,115
JZ NTASIDES
NTADXDES:
  MOV CX,0
  MOV AX,0
  MOV AL,[SI+7] 
  MOV CL,[SI+8]
  ADD AX,CX
  CMP AX,217
  JZ NTADXDESWAXSOURCE
  CMP AX,218 
  JZ NTADXDESWBXSOURCE
  CMP AX,219
  JZ NTADXDESWCXSOURCE
  CMP AX,220
 JZ NTADXDESWDXORSISOURCE
 CMP AX,205
 JZ NTADXDESWDIORALLWALERROR
 MOV BX,0
 MOV CX,0                              ;TAKECARE
 MOV CL,[SI+9]
 MOV BL,[SI+10]
 ADD CX,BX
 ADD AX,CX
 CMP AX,402
 JZ DXDES_WNTA_MEMBX
 CMP AX,404              
 JZ NTA_DXDES_WMEMSI
 CMP AX,389
 JZ NTA_DXDES_WMEMDI
 JMP NTADXDESW_RKM_YA_MEMRKM_YAERROR  
 
 NTADXDESWAXSOURCE:  
 MOV AX,RAX1
 MOV RDX1,AX
 JMP NAG7
 
 NTADXDESWBXSOURCE: 
 MOV AX,RBX1
 MOV RDX1,AX
 JMP NAG7
 NTADXDESWCXSOURCE:
 MOV AX,RCX1
 MOV RDX1,AX
 JMP NAG7
 NTADXDESWDXORSISOURCE:
 MOV AL,[SI+7]
 CMP AL,100
 JZ NTADXDESWDXSOURCE
  
NTADXDESWSISOURCE:
MOV BX,ISI1
MOV RDX1,BX
JMP NAG7
NTADXDESWDXSOURCE:
JMP NAG7
NTADXDESWDIORALLWALERROR: 
MOV AL,[SI+7]
CMP AL,100 
JZ NTADXDESWDISOURCE
JMP ERROR
NTADXDESWDISOURCE:
MOV BX,IDI1
MOV RDX1,BX
JMP NAG7
DXDES_WNTA_MEMBX:
MOV BX,RBX1
CMP BX,0FH
JA ERROR
MOV AH, MEMORY[BX+1]
MOV AL, MEMORY[BX]
MOV RDX1,AX
JMP NAG7
 NTA_DXDES_WMEMSI:
MOV BX,ISI1
CMP BX,0FH
JA ERROR
MOV AH, MEMORY[BX+1]
MOV AL, MEMORY[BX]
MOV RDX1,AX
JMP NAG7
NTA_DXDES_WMEMDI:
MOV BX,IDI1
CMP BX,0FH
JA ERROR
MOV AH, MEMORY[BX+1]
MOV AL, MEMORY[BX]
MOV RDX1,AX
JMP NAG7
NTADXDESW_RKM_YA_MEMRKM_YAERROR:
MOV AL,[SI+7]
CMP AL,91
JZ MEMRKM_ORERROR_DXDES

RKM_ORERROR_DXDES:
MOV AL,[SI+8]
CMP AL,108
JZ ERROR
CMP AL,104
JZ ERROR
RET_NUM_COUNT  COMp1+7
CMP CX,4
JA ERROR
MOV RDX1,DX
JMP NAG7
MEMRKM_ORERROR_DXDES:
MOV AL,[SI+9]
CMP AL,108
JZ ERROR
CMP AL,104
JZ ERROR
RET_NUM_COUNT  COMp1+8
CMP CX,4
JA ERROR
CMP DX,0FH
JA ERROR
MOV BX,DX
MOV AH, MEMORY[BX+1]
MOV AL, MEMORY[BX]
MOV RDX1,AX
JMP NAG7
;//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
NTASIDES:
  MOV CX,0
  MOV AX,0
  MOV AL,[SI+7] 
  MOV CL,[SI+8]
  ADD AX,CX
  CMP AX,217
  JZ NTASIDESWAXSOURCE
  CMP AX,218 
  JZ NTASIDESWBXSOURCE
  CMP AX,219
  JZ NTASIDESWCXSOURCE
  CMP AX,220
 JZ NTASIDESWDXORSISOURCE
 CMP AX,205
 JZ NTASIDESWDIORALLWALERROR
 MOV BX,0
 MOV CX,0                              ;TAKECARE
 MOV CL,[SI+9]
 MOV BL,[SI+10]
 ADD CX,BX
 ADD AX,CX
 CMP AX,402
 JZ SIDES_WNTA_MEMBX
 CMP AX,404              
 JZ NTA_SIDES_WMEMSI
 CMP AX,389
 JZ NTA_SIDES_WMEMDI
 JMP NTASIDESW_RKM_YA_MEMRKM_YAERROR  
 
 NTASIDESWAXSOURCE:  
 MOV AX,RAX1
 MOV ISI1,AX
 JMP NAG7
 
 NTASIDESWBXSOURCE: 
 MOV AX,RBX1
 MOV ISI1,AX
 JMP NAG7
 NTASIDESWCXSOURCE:
 MOV AX,RCX1
 MOV ISI1,AX
 JMP NAG7
 NTASIDESWDXORSISOURCE:
 MOV AL,[SI+7]
 CMP AL,100
 JZ NTASIDESWDXSOURCE
  
NTASIDESWSISOURCE:
JMP NAG7
NTASIDESWDXSOURCE:
MOV AX,RDX1
 MOV ISI1,AX
 JMP NAG7
NTASIDESWDIORALLWALERROR: 
MOV AL,[SI+7]
CMP AL,100 
JZ NTASIDESWDISOURCE
JMP ERROR
NTASIDESWDISOURCE:
MOV BX,IDI1
MOV ISI1,BX
JMP NAG7
SIDES_WNTA_MEMBX:
MOV BX,RBX1
CMP BX,0FH
JA ERROR
MOV AH, MEMORY[BX+1]
MOV AL, MEMORY[BX]
MOV ISI1,AX
JMP NAG7
 NTA_SIDES_WMEMSI:
MOV BX,ISI1
CMP BX,0FH
JA ERROR
MOV AH, MEMORY[BX+1]
MOV AL, MEMORY[BX]
MOV ISI1,AX
JMP NAG7
NTA_SIDES_WMEMDI:
MOV BX,IDI1
CMP BX,0FH
JA ERROR
MOV AH, MEMORY[BX+1]
MOV AL, MEMORY[BX]
MOV ISI1,AX
JMP NAG7
NTASIDESW_RKM_YA_MEMRKM_YAERROR:
MOV AL,[SI+7]
CMP AL,91
JZ MEMRKM_ORERROR_SIDES

RKM_ORERROR_SIDES:
MOV AL,[SI+8]
CMP AL,108
JZ ERROR
CMP AL,104
JZ ERROR
RET_NUM_COUNT  COMp1+7
CMP CX,4
JA ERROR
MOV ISI1,DX
JMP NAG7
MEMRKM_ORERROR_SIDES:
MOV AL,[SI+9]
CMP AL,108
JZ ERROR
CMP AL,104
JZ ERROR
RET_NUM_COUNT  COMp1+8
CMP CX,4
JA ERROR
CMP DX,0FH
JA ERROR
MOV BX,DX
MOV AH, MEMORY[BX+1]
MOV AL, MEMORY[BX]
MOV ISI1,AX
JMP NAG7
;///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

NTADIORALDES:
MOV AL,[SI+4]
CMP AL,97
JZ NTAALDES
NTADIDES:
  MOV CX,0
  MOV AX,0
  MOV AL,[SI+7] 
  MOV CL,[SI+8]
  ADD AX,CX
  CMP AX,217
  JZ NTADIDESWAXSOURCE
  CMP AX,218 
  JZ NTADIDESWBXSOURCE
  CMP AX,219
  JZ NTADIDESWCXSOURCE
  CMP AX,220
 JZ NTADIDESWDXORSISOURCE
 CMP AX,205
 JZ NTADIDESWDIORALLWALERROR
 MOV BX,0
 MOV CX,0                              ;TAKECARE
 MOV CL,[SI+9]
 MOV BL,[SI+10]
 ADD CX,BX
 ADD AX,CX
 CMP AX,402
 JZ DIDES_WNTA_MEMBX
 CMP AX,404              
 JZ NTA_DIDES_WMEMSI
 CMP AX,389
 JZ NTA_DIDES_WMEMDI
 JMP NTADIDESW_RKM_YA_MEMRKM_YAERROR  
 
 NTADIDESWAXSOURCE:  
 MOV AX,RAX1
 MOV IDI1,AX
 JMP NAG7
 
 NTADIDESWBXSOURCE: 
 MOV AX,RBX1
 MOV IDI1,AX
 JMP NAG7
 NTADIDESWCXSOURCE:
 MOV AX,RCX1
 MOV IDI1,AX
 JMP NAG7
 NTADIDESWDXORSISOURCE:
 MOV AL,[SI+7]
 CMP AL,100
 JZ NTADIDESWDXSOURCE
  
NTADIDESWSISOURCE:
MOV AX,ISI1
 MOV IDI1,AX
 JMP NAG7
NTADIDESWDXSOURCE:
MOV AX,RDX1
 MOV IDI1,AX
 JMP NAG7
NTADIDESWDIORALLWALERROR: 
MOV AL,[SI+7]
CMP AL,100 
JZ NTADIDESWDISOURCE
JMP ERROR
NTADIDESWDISOURCE:
JMP NAG7
DIDES_WNTA_MEMBX:
MOV BX,RBX1
CMP BX,0FH
JA ERROR
MOV AH, MEMORY[BX+1]
MOV AL, MEMORY[BX]
MOV IDI1,AX
JMP NAG7
 NTA_DIDES_WMEMSI:
MOV BX,ISI1
CMP BX,0FH
JA ERROR
MOV AH, MEMORY[BX+1]
MOV AL, MEMORY[BX]
MOV IDI1,AX
JMP NAG7
NTA_DIDES_WMEMDI:
MOV BX,IDI1
CMP BX,0FH
JA ERROR
MOV AH, MEMORY[BX+1]
MOV AL, MEMORY[BX]
MOV IDI1,AX
JMP NAG7
NTADIDESW_RKM_YA_MEMRKM_YAERROR:
MOV AL,[SI+7]
CMP AL,91
JZ MEMRKM_ORERROR_DIDES

RKM_ORERROR_DIDES:
MOV AL,[SI+8]
CMP AL,108
JZ ERROR
CMP AL,104
JZ ERROR
RET_NUM_COUNT  COMp1+7
CMP CX,4
JA ERROR
MOV IDI1,DX
JMP NAG7
MEMRKM_ORERROR_DIDES:
MOV AL,[SI+9]
CMP AL,108
JZ ERROR
CMP AL,104
JZ ERROR
RET_NUM_COUNT  COMp1+8
CMP CX,4
JA ERROR
CMP DX,0FH
JA ERROR
MOV BX,DX
MOV AH, MEMORY[BX+1]
MOV AL, MEMORY[BX]
MOV IDI1,AX
JMP NAG7
;////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
NTAALDES:
  MOV CX,0
  MOV AX,0
  MOV AL,[SI+7] 
  MOV CL,[SI+8]
  ADD AX,CX
  CMP AX,217
  JZ ERROR
  CMP AX,218 
  JZ ERROR
  CMP AX,219
  JZ ERROR
  CMP AX,220
 JZ ERROR
 CMP AX,205
 JZ NTAALDESWDIORALLWDIERROR
 CMP AX,201
 JZ NTAALDESWAHSOURCE
 CMP AX,206
 JZ NTAALDESWBLSOURCE
 CMP AX,202
 JZ NTAALDESWBHSOURCE 
 CMP AX,207
 JZ NTAALDESWCLSOURCE
 CMP AX,203
 JZ NTAALDESWCHSOURCE
 CMP AX,208
 JZ NTAALDESWDLSOURCE
 CMP AX,204
 JZ NTAALDESWDHSOURCE 
 MOV BX,0
 MOV CX,0                              ;TAKECARE
 MOV CL,[SI+9]
 MOV BL,[SI+10]
 ADD CX,BX
 ADD AX,CX
 CMP AX,402
 JZ ALDES_WNTA_MEMBX
 CMP AX,404              
 JZ NTA_ALDES_WMEMSI
 CMP AX,389
 JZ NTA_ALDES_WMEMDI
 JMP NTAALDESW_RKM_YA_MEMRKM_YAERROR  
 
 
  
NTAALDESWDIORALLWDIERROR: 
MOV AL,[SI+7]
CMP AL,100 
JZ ERROR
NTAALDESWALSOURCE:
JMP NAG7
ALDES_WNTA_MEMBX:
MOV BX,RBX1
CMP BX,0FH
JA ERROR
MOV CX,0
MOV CL,MEMORY[BX] 
MOV BX,100H                        ;MA3 AL CODE W MA3 AH CODE
MOV AX,RAX1
DIV BX
SHL AX,8
ADD AX,CX
MOV RAX1,AX
JMP NAG7
NTA_ALDES_WMEMSI:
MOV BX,ISI1
CMP BX,0FH
JA ERROR
MOV CX,0
MOV CL,MEMORY[BX]
MOV BX,100H
MOV AX,RAX1
DIV BX
SHL AX,8
ADD AX,CX
MOV RAX1,AX
JMP NAG7
NTA_ALDES_WMEMDI:
MOV BX,IDI1
CMP BX,0FH
JA ERROR
MOV CX,0
MOV CL,MEMORY[BX]
MOV BX,100H
MOV AX,RAX1
DIV BX
SHL AX,8
ADD AX,CX
MOV RAX1,AX
JMP NAG7
NTAALDESWAHSOURCE:
MOV BX,100H
MOV AX,RAX1
DIV BX
MOV AH,0
MOV CX,AX
MOV AX,RAX1
DIV BX
SHL AX,8
ADD AX,CX
MOV RAX1,AX
JMP NAG7
NTAALDESWBLSOURCE:
MOV CX,RBX1
ROR CX,8
SHR CX,8
MOV BX,100H
MOV AX,RAX1
DIV BX
SHL AX,8
ADD AX,CX
MOV RAX1,AX
JMP NAG7
NTAALDESWBHSOURCE:
MOV BX,100H
MOV AX,RBX1
DIV BX
MOV AH,0
MOV CX,AX
MOV AX,RAX1
DIV BX
SHL AX,8
ADD AX,CX
MOV RAX1,AX
JMP NAG7
NTAALDESWCLSOURCE:
MOV CX,RCX1
ROR CX,8
SHR CX,8
MOV BX,100H
MOV AX,RAX1
DIV BX
SHL AX,8
ADD AX,CX
MOV RAX1,AX
JMP NAG7
NTAALDESWCHSOURCE:
MOV BX,100H
MOV AX,RCX1
DIV BX
MOV AH,0
MOV CX,AX
MOV AX,RAX1
DIV BX
SHL AX,8
ADD AX,CX
MOV RAX1,AX
JMP NAG7
NTAALDESWDLSOURCE:
MOV CX,RDX1
ROR CX,8
SHR CX,8
MOV BX,100H
MOV AX,RAX1
DIV BX
SHL AX,8
ADD AX,CX
MOV RAX1,AX
JMP NAG7
NTAALDESWDHSOURCE:
MOV BX,100H
MOV AX,RDX1
DIV BX
MOV AH,0
MOV CX,AX
MOV AX,RAX1
DIV BX
SHL AX,8
ADD AX,CX
MOV RAX1,AX
JMP NAG7
NTAALDESW_RKM_YA_MEMRKM_YAERROR:
MOV AL,[SI+7]
CMP AL,91
JZ MEMRKM_ORERROR_ALDES

RKM_ORERROR_ALDES:
MOV AL,[SI+8]
RET_NUM_COUNT  COMp1+7
CMP CX,2
JA ERROR
MOV AX,RAX1
MOV BX,100H
PUSH DX
DIV BX
POP DX
SHL AX,8
ADD AX,DX
MOV RAX1,AX
JMP NAG7
MEMRKM_ORERROR_ALDES:
MOV AL,[SI+9]
CMP AL,108
JZ ERROR
CMP AL,104
JZ ERROR
RET_NUM_COUNT  COMp1+8
CMP CX,4
JA ERROR
CMP DX,0FH
JA ERROR
MOV BX,DX
MOV CX,0
MOV CL,MEMORY[BX]
MOV AX,RAX1
MOV BX,100H
DIV BX
SHL AX,8
ADD AX,CX
MOV RAX1,AX
JMP NAG7
;////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
NTABLDIS:
  MOV CX,0
  MOV AX,0
  MOV AL,[SI+7] 
  MOV CL,[SI+8]
  ADD AX,CX
  CMP AX,217
  JZ ERROR
  CMP AX,218 
  JZ ERROR
  CMP AX,219
  JZ ERROR
  CMP AX,220
 JZ ERROR
 CMP AX,205
 JZ NTABLDESWDIORALLWDIERROR
 CMP AX,201
 JZ NTABLDESWAHSOURCE
 CMP AX,206
 JZ NTABLDESWBLSOURCE
 CMP AX,202
 JZ NTABLDESWBHSOURCE 
 CMP AX,207
 JZ NTABLDESWCLSOURCE
 CMP AX,203
 JZ NTABLDESWCHSOURCE
 CMP AX,208
 JZ NTABLDESWDLSOURCE
 CMP AX,204
 JZ NTABLDESWDHSOURCE 
 MOV BX,0
 MOV CX,0                              ;TAKECARE
 MOV CL,[SI+9]
 MOV BL,[SI+10]
 ADD CX,BX
 ADD AX,CX
 CMP AX,402
 JZ BLDES_WNTA_MEMBX
 CMP AX,404              
 JZ NTA_BLDES_WMEMSI
 CMP AX,389
 JZ NTA_BLDES_WMEMDI
 JMP NTABLDESW_RKM_YA_MEMRKM_YAERROR  
 
 
  
NTABLDESWDIORALLWDIERROR: 
MOV AL,[SI+7]
CMP AL,100 
JZ ERROR
NTABLDESWALSOURCE:
MOV CX,RAX1
ROR CX,8
SHR CX,8
MOV BX,100H
MOV AX,RBX1
DIV BX
SHL AX,8
ADD AX,CX
MOV RBX1,AX
JMP NAG7
BLDES_WNTA_MEMBX:
MOV BX,RBX1
CMP BX,0FH
JA ERROR
MOV CX,0
MOV CL,MEMORY[BX] 
MOV BX,100H                        ;MA3 AL CODE W MA3 AH CODE
MOV AX,RBX1
DIV BX
SHL AX,8
ADD AX,CX
MOV RBX1,AX
JMP NAG7
NTA_BLDES_WMEMSI:
MOV BX,ISI1
CMP BX,0FH
JA ERROR
MOV CX,0
MOV CL,MEMORY[BX]
MOV BX,100H
MOV AX,RBX1
DIV BX
SHL AX,8
ADD AX,CX
MOV RBX1,AX
JMP NAG7
NTA_BLDES_WMEMDI:
MOV BX,IDI1
CMP BX,0FH
JA ERROR
MOV CX,0
MOV CL,MEMORY[BX]
MOV BX,100H
MOV AX,RBX1
DIV BX
SHL AX,8
ADD AX,CX
MOV RBX1,AX
JMP NAG7
NTABLDESWAHSOURCE:
MOV BX,100H
MOV AX,RAX1
DIV BX
MOV AH,0
MOV CX,AX                  ;5LEBALK2SLLCODEALAH,BLBH,CL,CH
MOV AX,RBX1
DIV BX
SHL AX,8
ADD AX,CX
MOV RBX1,AX
JMP NAG7
NTABLDESWBLSOURCE:
JMP NAG7
NTABLDESWBHSOURCE:
MOV BX,100H
MOV AX,RBX1
DIV BX
MOV AH,0
MOV CX,AX
MOV AX,RBX1
DIV BX
SHL AX,8
ADD AX,CX
MOV RBX1,AX
JMP NAG7
NTABLDESWCLSOURCE:
MOV CX,RCX1
ROR CX,8
SHR CX,8
MOV BX,100H
MOV AX,RBX1
DIV BX
SHL AX,8
ADD AX,CX
MOV RBX1,AX
JMP NAG7
NTABLDESWCHSOURCE:
MOV BX,100H
MOV AX,RCX1
DIV BX
MOV AH,0
MOV CX,AX
MOV AX,RBX1
DIV BX
SHL AX,8
ADD AX,CX
MOV RBX1,AX
JMP NAG7
NTABLDESWDLSOURCE:
MOV CX,RDX1
ROR CX,8
SHR CX,8
MOV BX,100H
MOV AX,RBX1
DIV BX
SHL AX,8
ADD AX,CX
MOV RBX1,AX
JMP NAG7
NTABLDESWDHSOURCE:
MOV BX,100H
MOV AX,RDX1
DIV BX
MOV AH,0
MOV CX,AX
MOV AX,RBX1
DIV BX
SHL AX,8
ADD AX,CX
MOV RBX1,AX
JMP NAG7
NTABLDESW_RKM_YA_MEMRKM_YAERROR:
MOV AL,[SI+7]
CMP AL,91
JZ MEMRKM_ORERROR_BLDES

RKM_ORERROR_BLDES:
MOV AL,[SI+8]
RET_NUM_COUNT  COMp1+7
CMP CX,2
JA ERROR
MOV AX,RBX1
MOV BX,100H
PUSH DX
DIV BX 
POP DX
SHL AX,8
ADD AX,DX
MOV RBX1,AX
JMP NAG7
MEMRKM_ORERROR_BLDES:
MOV AL,[SI+9]
CMP AL,108
JZ ERROR
CMP AL,104
JZ ERROR
RET_NUM_COUNT  COMp1+8
CMP CX,4
JA ERROR
CMP DX,0FH
JA ERROR
MOV BX,DX
MOV CX,0
MOV CL,MEMORY[BX]
MOV AX,RBX1
MOV BX,100H
DIV BX
SHL AX,8
ADD AX,CX
MOV RBX1,AX
JMP NAG7
;/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
NTACLDIS:             ;3DLCODEDYAMEGS
  MOV CX,0
  MOV AX,0
  MOV AL,[SI+7] 
  MOV CL,[SI+8]
  ADD AX,CX
  CMP AX,217
  JZ ERROR
  CMP AX,218 
  JZ ERROR
  CMP AX,219
  JZ ERROR
  CMP AX,220
 JZ ERROR
 CMP AX,205
 JZ NTACLDESWDIORALLWDIERROR
 CMP AX,201
 JZ NTACLDESWAHSOURCE
 CMP AX,206
 JZ NTACLDESWBLSOURCE
 CMP AX,202
 JZ NTACLDESWBHSOURCE 
 CMP AX,207
 JZ NTACLDESWCLSOURCE
 CMP AX,203
 JZ NTACLDESWCHSOURCE
 CMP AX,208
 JZ NTACLDESWDLSOURCE
 CMP AX,204
 JZ NTACLDESWDHSOURCE   
 MOV BX,0
 MOV CX,0                              ;TAKECARE
 MOV CL,[SI+9]
 MOV BL,[SI+10]
 ADD CX,BX
 ADD AX,CX
 CMP AX,402
 JZ CLDES_WNTA_MEMBX
 CMP AX,404              
 JZ NTA_CLDES_WMEMSI
 CMP AX,389
 JZ NTA_CLDES_WMEMDI
  
 JMP NTACLDESW_RKM_YA_MEMRKM_YAERROR  
 
 
  
NTACLDESWDIORALLWDIERROR: 
MOV AL,[SI+7]
CMP AL,100 
JZ ERROR
NTACLDESWALSOURCE:
MOV CX,RAX1
ROR CX,8
SHR CX,8
MOV BX,100H
MOV AX,RCX1
DIV BX
SHL AX,8
ADD AX,CX
MOV RCX1,AX
JMP NAG7
CLDES_WNTA_MEMBX:
MOV BX,RBX1
CMP BX,0FH
JA ERROR
MOV CX,0
MOV CL,MEMORY[BX] 
MOV BX,100H                        ;MA3 AL CODE W MA3 AH CODE
MOV AX,RCX1
DIV BX
SHL AX,8
ADD AX,CX
MOV RCX1,AX
JMP NAG7
NTA_CLDES_WMEMSI:
MOV BX,ISI1
CMP BX,0FH
JA ERROR
MOV CX,0
MOV CL,MEMORY[BX]
MOV BX,100H
MOV AX,RCX1
DIV BX
SHL AX,8
ADD AX,CX
MOV RCX1,AX
JMP NAG7
NTA_CLDES_WMEMDI:
MOV BX,IDI1
CMP BX,0FH
JA ERROR
MOV CX,0
MOV CL,MEMORY[BX]
MOV BX,100H
MOV AX,RCX1
DIV BX
SHL AX,8
ADD AX,CX
MOV RCX1,AX
JMP NAG7
NTACLDESWAHSOURCE:
MOV BX,100H
MOV AX,RAX1
DIV BX
MOV AH,0
MOV CX,AX                  ;5LEBALK2SLLCODEALAH,BLBH,CL,CH
MOV AX,RCX1
DIV BX
SHL AX,8
ADD AX,CX
MOV RCX1,AX
JMP NAG7
NTACLDESWBLSOURCE:
MOV CX,RBX1
ROR CX,8
SHR CX,8
MOV BX,100H
MOV AX,RCX1
DIV BX
SHL AX,8
ADD AX,CX
MOV RCX1,AX
JMP NAG7

NTACLDESWBHSOURCE:
MOV BX,100H
MOV AX,RBX1
DIV BX
MOV AH,0
MOV CX,AX
MOV AX,RCX1
DIV BX
SHL AX,8
ADD AX,CX
MOV RCX1,AX
JMP NAG7
NTACLDESWCLSOURCE:
JMP NAG7
NTACLDESWCHSOURCE:
MOV BX,100H
MOV AX,RCX1
DIV BX
MOV AH,0
MOV CX,AX
MOV AX,RCX1
DIV BX
SHL AX,8
ADD AX,CX
MOV RCX1,AX
JMP NAG7
NTACLDESWDLSOURCE:
MOV CX,RDX1
ROR CX,8
SHR CX,8
MOV BX,100H
MOV AX,RCX1
DIV BX
SHL AX,8
ADD AX,CX
MOV RCX1,AX
JMP NAG7
NTACLDESWDHSOURCE:
MOV BX,100H
MOV AX,RDX1
DIV BX
MOV AH,0
MOV CX,AX
MOV AX,RCX1
DIV BX
SHL AX,8
ADD AX,CX
MOV RCX1,AX
JMP NAG7
NTACLDESW_RKM_YA_MEMRKM_YAERROR:
MOV AL,[SI+7]
CMP AL,91
JZ MEMRKM_ORERROR_CLDES

RKM_ORERROR_CLDES:
MOV AL,[SI+8]
RET_NUM_COUNT  COMp1+7
CMP CX,2
JA ERROR
MOV AX,RCX1
MOV BX,100H
PUSH DX
DIV BX
POP DX
SHL AX,8
ADD AX,DX
MOV RCX1,AX
JMP NAG7
MEMRKM_ORERROR_CLDES:
MOV AL,[SI+9]
CMP AL,108
JZ ERROR
CMP AL,104
JZ ERROR
RET_NUM_COUNT  COMp1+8
CMP CX,4
JA ERROR
CMP DX,0FH
JA ERROR
MOV BX,DX
MOV CX,0
MOV CL,MEMORY[BX]
MOV AX,RCX1
MOV BX,100H
DIV BX
SHL AX,8
ADD AX,CX
MOV RCX1,AX
JMP NAG7
;////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
NTADLDIS:             ;3DLCODEDYAMEGS
  MOV CX,0
  MOV AX,0
  MOV AL,[SI+7] 
  MOV CL,[SI+8]
  ADD AX,CX
  CMP AX,217
  JZ ERROR
  CMP AX,218 
  JZ ERROR
  CMP AX,219
  JZ ERROR
  CMP AX,220
 JZ ERROR
 CMP AX,205
 JZ NTADLDESWDIORALLWDIERROR
 CMP AX,201
 JZ NTADLDESWAHSOURCE
 CMP AX,206
 JZ NTADLDESWBLSOURCE
 CMP AX,202
 JZ NTADLDESWBHSOURCE 
 CMP AX,207
 JZ NTADLDESWCLSOURCE
 CMP AX,203
 JZ NTADLDESWCHSOURCE
 CMP AX,208
 JZ NTADLDESWDLSOURCE
 CMP AX,204
 JZ NTADLDESWDHSOURCE    
 MOV BX,0
 MOV CX,0                              ;TAKECARE
 MOV CL,[SI+9]
 MOV BL,[SI+10]
 ADD CX,BX
 ADD AX,CX


 CMP AX,402
 JZ DLDES_WNTA_MEMBX
 CMP AX,404              
 JZ NTA_DLDES_WMEMSI
 CMP AX,389
 JZ NTA_DLDES_WMEMDI
 
 JMP NTADLDESW_RKM_YA_MEMRKM_YAERROR  
 
 
  
NTADLDESWDIORALLWDIERROR: 
MOV AL,[SI+7]
CMP AL,100 
JZ ERROR
NTADLDESWALSOURCE:
MOV CX,RAX1
ROR CX,8
SHR CX,8
MOV BX,100H
MOV AX,RDX1
DIV BX
SHL AX,8
ADD AX,CX
MOV RDX1,AX
JMP NAG7
DLDES_WNTA_MEMBX:
MOV BX,RBX1
CMP BX,0FH
JA ERROR
MOV CX,0
MOV CL,MEMORY[BX] 
MOV BX,100H                        ;MA3 AL CODE W MA3 AH CODE
MOV AX,RDX1
DIV BX
SHL AX,8
ADD AX,CX
MOV RDX1,AX
JMP NAG7
NTA_DLDES_WMEMSI:
MOV BX,ISI1
CMP BX,0FH
JA ERROR
MOV CX,0
MOV CL,MEMORY[BX]
MOV BX,100H
MOV AX,RDX1
DIV BX
SHL AX,8
ADD AX,CX
MOV RDX1,AX
JMP NAG7
NTA_DLDES_WMEMDI:
MOV BX,IDI1
CMP BX,0FH
JA ERROR
MOV CX,0
MOV CL,MEMORY[BX]
MOV BX,100H
MOV AX,RDX1
DIV BX
SHL AX,8
ADD AX,CX
MOV RDX1,AX
JMP NAG7
NTADLDESWAHSOURCE:
MOV BX,100H
MOV AX,RAX1
DIV BX
MOV AH,0
MOV CX,AX                  ;5LEBALK2SLLCODEALAH,BLBH,CL,CH
MOV AX,RDX1
DIV BX
SHL AX,8
ADD AX,CX
MOV RDX1,AX
JMP NAG7
NTADLDESWBLSOURCE:
MOV CX,RBX1
ROR CX,8
SHR CX,8
MOV BX,100H
MOV AX,RCX1
DIV BX
SHL AX,8
ADD AX,CX
MOV RDX1,AX
JMP NAG7

NTADLDESWBHSOURCE:
MOV BX,100H
MOV AX,RBX1
DIV BX
MOV AH,0
MOV CX,AX
MOV AX,RDX1
DIV BX
SHL AX,8
ADD AX,CX
MOV RDX1,AX
JMP NAG7
NTADLDESWCLSOURCE:
MOV CX,RCX1
ROR CX,8
SHR CX,8
MOV BX,100H
MOV AX,RDX1
DIV BX
SHL AX,8
ADD AX,CX
MOV RDX1,AX
JMP NAG7
NTADLDESWCHSOURCE:
MOV BX,100H
MOV AX,RCX1
DIV BX
MOV AH,0
MOV CX,AX
MOV AX,RDX1
DIV BX
SHL AX,8
ADD AX,CX
MOV RDX1,AX
JMP NAG7
NTADLDESWDLSOURCE:
JMP NAG7
NTADLDESWDHSOURCE:
MOV BX,100H
MOV AX,RDX1
DIV BX
MOV AH,0
MOV CX,AX
MOV AX,RDX1
DIV BX
SHL AX,8
ADD AX,CX
MOV RDX1,AX
JMP NAG7
NTADLDESW_RKM_YA_MEMRKM_YAERROR:
MOV AL,[SI+7]
CMP AL,91
JZ MEMRKM_ORERROR_DLDES

RKM_ORERROR_DLDES:
MOV AL,[SI+8]
RET_NUM_COUNT  COMp1+7
CMP CX,2
JA ERROR
MOV AX,RDX1
MOV BX,100H
PUSH DX
DIV BX
POP DX
SHL AX,8
ADD AX,DX
MOV RDX1,AX
JMP NAG7
MEMRKM_ORERROR_DLDES:
MOV AL,[SI+9]
CMP AL,108
JZ ERROR
CMP AL,104
JZ ERROR
RET_NUM_COUNT  COMp1+8
CMP CX,4
JA ERROR
CMP DX,0FH
JA ERROR
MOV BX,DX
MOV CX,0
MOV CL,MEMORY[BX]
MOV AX,RDX1
MOV BX,100H
DIV BX
SHL AX,8
ADD AX,CX
MOV RDX1,AX
JMP NAG7
;/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
NTAAHDIS:
  MOV CX,0
  MOV AX,0
  MOV AL,[SI+7] 
  MOV CL,[SI+8]
  ADD AX,CX
  CMP AX,217
  JZ ERROR
  CMP AX,218 
  JZ ERROR
  CMP AX,219
  JZ ERROR
  CMP AX,220
 JZ ERROR
 CMP AX,205
 JZ NTAAHDESWDIORALLWDIERROR
 CMP AX,201
 JZ NTAAHDESWAHSOURCE
 CMP AX,206
 JZ NTAAHDESWBLSOURCE
 CMP AX,202
 JZ NTAAHDESWBHSOURCE 
 CMP AX,207
 JZ NTAAHDESWCLSOURCE
 CMP AX,203
 JZ NTAAHDESWCHSOURCE
 CMP AX,208
 JZ NTAAHDESWDLSOURCE
 CMP AX,204
 JZ NTAAHDESWDHSOURCE   
 MOV BX,0
 MOV CX,0                              ;TAKECARE
 MOV CL,[SI+9]
 MOV BL,[SI+10]
 ADD CX,BX
 ADD AX,CX

 CMP AX,402
 JZ AHDES_WNTA_MEMBX
 CMP AX,404              
 JZ NTA_AHDES_WMEMSI
 CMP AX,389
 JZ NTA_AHDES_WMEMDI
  
 JMP NTAAHDESW_RKM_YA_MEMRKM_YAERROR  
 
 
  
NTAAHDESWDIORALLWDIERROR: 
MOV AL,[SI+7]
CMP AL,100 
JZ ERROR
NTAAHDESWALSOURCE:
MOV CX,RAX1
ROR CX,8
SHR CX,8
ROL CX,8
MOV AX,RAX1
ROR AX,8
SHR AX,8
ADD AX,CX
MOV RAX1,AX
JMP NAG7
AHDES_WNTA_MEMBX:
MOV BX,RBX1
CMP BX,0FH
JA ERROR
MOV CX,0
MOV CH,MEMORY[BX] 
MOV AX,RAX1
ROR AX,8
SHR AX,8
ADD AX,CX              ;MA3 AL CODE W MA3 AH CO
MOV RAX1,AX
JMP NAG7
NTA_AHDES_WMEMSI:
MOV BX,ISI1
CMP BX,0FH
JA ERROR
MOV CX,0
MOV CH,MEMORY[BX] 
MOV AX,RAX1
ROR AX,8
SHR AX,8
ADD AX,CX              ;MA3 AL CODE W MA3 AH CO
MOV RAX1,AX
JMP NAG7
NTA_AHDES_WMEMDI:
MOV BX,IDI1
CMP BX,0FH
JA ERROR
MOV CX,0
MOV CH,MEMORY[BX] 
MOV AX,RAX1
ROR AX,8
SHR AX,8
ADD AX,CX              ;MA3 AL CODE W MA3 AH CO
MOV RAX1,AX
JMP NAG7
NTAAHDESWAHSOURCE:
JMP NAG7
NTAAHDESWBLSOURCE:
MOV CX,RBX1
ROR CX,8
SHR CX,8
ROL CX,8
MOV AX,RAX1
ROR AX,8
SHR AX,8
ADD AX,CX
MOV RAX1,AX
JMP NAG7
NTAAHDESWBHSOURCE:
MOV CX,RBX1
MOV AX,CX
MOV BX,100H
DIV BX
SHL AX,8
MOV CX,AX
MOV AX,RAX1
ROR AX,8
SHR AX,8
ADD AX,CX
MOV RAX1,AX
JMP NAG7
NTAAHDESWCLSOURCE:
MOV CX,RCX1
ROR CX,8
SHR CX,8
ROL CX,8
MOV AX,RAX1
ROR AX,8
SHR AX,8
ADD AX,CX
MOV RAX1,AX
JMP NAG7
NTAAHDESWCHSOURCE:
MOV CX,RCX1
MOV AX,CX
MOV BX,100H
DIV BX
SHL AX,8
MOV CX,AX
MOV AX,RAX1
ROR AX,8
SHR AX,8
ADD AX,CX
MOV RAX1,AX
JMP NAG7
NTAAHDESWDLSOURCE:
MOV CX,RDX1
ROR CX,8
SHR CX,8
ROL CX,8
MOV AX,RAX1
ROR AX,8
SHR AX,8
ADD AX,CX
MOV RAX1,AX
JMP NAG7
NTAAHDESWDHSOURCE:
MOV CX,RDX1
MOV AX,CX
MOV BX,100H
DIV BX
SHL AX,8
MOV CX,AX
MOV AX,RAX1
ROR AX,8
SHR AX,8
ADD AX,CX
MOV RAX1,AX
JMP NAG7
NTAAHDESW_RKM_YA_MEMRKM_YAERROR:
MOV AL,[SI+7]
CMP AL,91
JZ MEMRKM_ORERROR_AHDES

RKM_ORERROR_AHDES:
MOV AL,[SI+8]
RET_NUM_COUNT  COMp1+7
CMP CX,2
JA ERROR
MOV AX,RAX1
ROR AX,8
SHR AX,8
SHL DX,8
ADD AX,DX
MOV RAX1,AX
JMP NAG7
MEMRKM_ORERROR_AHDES:
MOV AL,[SI+9]
CMP AL,108
JZ ERROR
CMP AL,104
JZ ERROR
RET_NUM_COUNT  COMp1+8
CMP CX,4
JA ERROR
CMP DX,0FH
JA ERROR
MOV BX,DX
MOV CX,0
MOV CH,MEMORY[BX]
MOV AX,RAX1
ROR AX,8
SHR AX,8
ADD AX,CX
MOV RAX1,AX
JMP NAG7
 ;///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
NTABHDIS:
  MOV CX,0
  MOV AX,0
  MOV AL,[SI+7] 
  MOV CL,[SI+8]
  ADD AX,CX
  CMP AX,217
  JZ ERROR
  CMP AX,218 
  JZ ERROR
  CMP AX,219
  JZ ERROR
  CMP AX,220
 JZ ERROR
 CMP AX,205
 JZ NTABHDESWDIORALLWDIERROR
 CMP AX,201
 JZ NTABHDESWAHSOURCE
 CMP AX,206
 JZ NTABHDESWBLSOURCE
 CMP AX,202
 JZ NTABHDESWBHSOURCE 
 CMP AX,207
 JZ NTABHDESWCLSOURCE
 CMP AX,203
 JZ NTABHDESWCHSOURCE
 CMP AX,208
 JZ NTABHDESWDLSOURCE
 CMP AX,204
 JZ NTABHDESWDHSOURCE   
 MOV BX,0
 MOV CX,0                              ;TAKECARE
 MOV CL,[SI+9]
 MOV BL,[SI+10]
 ADD CX,BX
 ADD AX,CX
 CMP AX,402
 JZ BHDES_WNTA_MEMBX
 CMP AX,404              
 JZ NTA_BHDES_WMEMSI
 CMP AX,389
 JZ NTA_BHDES_WMEMDI
  
 JMP NTABHDESW_RKM_YA_MEMRKM_YAERROR  
 
 
  
NTABHDESWDIORALLWDIERROR: 
MOV AL,[SI+7]
CMP AL,100 
JZ ERROR
NTABHDESWALSOURCE:
MOV CX,RAX1
ROR CX,8
SHR CX,8
ROL CX,8
MOV AX,RBX1
ROR AX,8
SHR AX,8
ADD AX,CX
MOV RBX1,AX
JMP NAG7
BHDES_WNTA_MEMBX:
MOV BX,RBX1
CMP BX,0FH
JA ERROR
MOV CX,0
MOV CH,MEMORY[BX] 
MOV AX,RBX1
ROR AX,8
SHR AX,8
ADD AX,CX              ;MA3 AL CODE W MA3 AH CO
MOV RBX1,AX
JMP NAG7
NTA_BHDES_WMEMSI:
MOV BX,ISI1
CMP BX,0FH
JA ERROR
MOV CX,0
MOV CH,MEMORY[BX] 
MOV AX,RBX1
ROR AX,8
SHR AX,8
ADD AX,CX              ;MA3 AL CODE W MA3 AH CO
MOV RBX1,AX
JMP NAG7
NTA_BHDES_WMEMDI:
MOV BX,IDI1
CMP BX,0FH
JA ERROR
MOV CX,0
MOV CH,MEMORY[BX] 
MOV AX,RBX1
ROR AX,8
SHR AX,8
ADD AX,CX              ;MA3 AL CODE W MA3 AH CO
MOV RBX1,AX
JMP NAG7
NTABHDESWAHSOURCE:
MOV CX,RAX1
MOV AX,CX
MOV BX,100H
DIV BX
SHL AX,8
MOV CX,AX
MOV AX,RBX1
ROR AX,8
SHR AX,8
ADD AX,CX
MOV RBX1,AX
JMP NAG7
NTABHDESWBLSOURCE:
MOV CX,RBX1
ROR CX,8
SHR CX,8
ROL CX,8
MOV AX,RBX1
ROR AX,8
SHR AX,8
ADD AX,CX
MOV RBX1,AX
JMP NAG7
NTABHDESWBHSOURCE:
JMP NAG7
NTABHDESWCLSOURCE:
MOV CX,RCX1
ROR CX,8
SHR CX,8
ROL CX,8
MOV AX,RBX1
ROR AX,8
SHR AX,8
ADD AX,CX
MOV RBX1,AX
JMP NAG7
NTABHDESWCHSOURCE:
MOV CX,RCX1
MOV AX,CX
MOV BX,100H
DIV BX
SHL AX,8
MOV CX,AX
MOV AX,RBX1
ROR AX,8
SHR AX,8
ADD AX,CX
MOV RBX1,AX
JMP NAG7
NTABHDESWDLSOURCE:
MOV CX,RDX1
ROR CX,8
SHR CX,8
ROL CX,8
MOV AX,RBX1
ROR AX,8
SHR AX,8
ADD AX,CX
MOV RBX1,AX
JMP NAG7
NTABHDESWDHSOURCE:
MOV CX,RDX1
MOV AX,CX
MOV BX,100H
DIV BX
SHL AX,8
MOV CX,AX
MOV AX,RBX1
ROR AX,8
SHR AX,8
ADD AX,CX
MOV RBX1,AX
JMP NAG7
NTABHDESW_RKM_YA_MEMRKM_YAERROR:
MOV AL,[SI+7]
CMP AL,91
JZ MEMRKM_ORERROR_BHDES

RKM_ORERROR_BHDES:
MOV AL,[SI+8]
RET_NUM_COUNT  COMp1+7
CMP CX,2
JA ERROR
MOV AX,RBX1
ROR AX,8
SHR AX,8
SHL DX,8
ADD AX,DX
MOV RBX1,AX
JMP NAG7
MEMRKM_ORERROR_BHDES:
MOV AL,[SI+9]
CMP AL,108
JZ ERROR
CMP AL,104
JZ ERROR
RET_NUM_COUNT  COMp1+8
CMP CX,4
JA ERROR
CMP DX,0FH
JA ERROR
MOV BX,DX
MOV CX,0
MOV CH,MEMORY[BX]
MOV AX,RBX1
ROR AX,8
SHR AX,8
ADD AX,CX
MOV RBX1,AX
JMP NAG7
;//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
NTACHDIS:
  MOV CX,0
  MOV AX,0
  MOV AL,[SI+7] 
  MOV CL,[SI+8]
  ADD AX,CX
  CMP AX,217
  JZ ERROR
  CMP AX,218 
  JZ ERROR
  CMP AX,219
  JZ ERROR
  CMP AX,220
 JZ ERROR
 CMP AX,205
 JZ NTACHDESWDIORALLWDIERROR
 CMP AX,201
 JZ NTACHDESWAHSOURCE
 CMP AX,206
 JZ NTACHDESWBLSOURCE
 CMP AX,202
 JZ NTACHDESWBHSOURCE 
 CMP AX,207
 JZ NTACHDESWCLSOURCE
 CMP AX,203
 JZ NTACHDESWCHSOURCE
 CMP AX,208
 JZ NTACHDESWDLSOURCE
 CMP AX,204
 JZ NTACHDESWDHSOURCE
 MOV BX,0
 MOV CX,0                              ;TAKECARE
 MOV CL,[SI+9]
 MOV BL,[SI+10]
 ADD CX,BX
 ADD AX,CX
 CMP AX,402
 JZ CHDES_WNTA_MEMBX
 CMP AX,404              
 JZ NTA_CHDES_WMEMSI
 CMP AX,389
 JZ NTA_CHDES_WMEMDI
  
 JMP NTACHDESW_RKM_YA_MEMRKM_YAERROR  
 
 
  
NTACHDESWDIORALLWDIERROR: 
MOV AL,[SI+7]
CMP AL,100 
JZ ERROR
NTACHDESWALSOURCE:
MOV CX,RAX1
ROR CX,8
SHR CX,8
ROL CX,8
MOV AX,RCX1
ROR AX,8
SHR AX,8
ADD AX,CX
MOV RCX1,AX
JMP NAG7
CHDES_WNTA_MEMBX:
MOV BX,RBX1
CMP BX,0FH
JA ERROR
MOV CX,0
MOV CH,MEMORY[BX] 
MOV AX,RCX1
ROR AX,8
SHR AX,8
ADD AX,CX              ;MA3 AL CODE W MA3 AH CO
MOV RCX1,AX
JMP NAG7
NTA_CHDES_WMEMSI:
MOV BX,ISI1
CMP BX,0FH
JA ERROR
MOV CX,0
MOV CH,MEMORY[BX] 
MOV AX,RCX1
ROR AX,8
SHR AX,8
ADD AX,CX              ;MA3 AL CODE W MA3 AH CO
MOV RCX1,AX
JMP NAG7
NTA_CHDES_WMEMDI:
MOV BX,IDI1
CMP BX,0FH
JA ERROR
MOV CX,0
MOV CH,MEMORY[BX] 
MOV AX,RCX1
ROR AX,8
SHR AX,8
ADD AX,CX              ;MA3 AL CODE W MA3 AH CO
MOV RCX1,AX
JMP NAG7
NTACHDESWAHSOURCE:
MOV CX,RAX1
MOV AX,CX
MOV BX,100H
DIV BX
SHL AX,8
MOV CX,AX
MOV AX,RCX1
ROR AX,8
SHR AX,8
ADD AX,CX
MOV RCX1,AX
JMP NAG7
NTACHDESWBLSOURCE:
MOV CX,RBX1
ROR CX,8
SHR CX,8
ROL CX,8
MOV AX,RCX1
ROR AX,8
SHR AX,8
ADD AX,CX
MOV RCX1,AX
JMP NAG7
NTACHDESWBHSOURCE:
MOV CX,RBX1
MOV AX,CX
MOV BX,100H
DIV BX
SHL AX,8
MOV CX,AX
MOV AX,RCX1
ROR AX,8
SHR AX,8
ADD AX,CX
MOV RCX1,AX
JMP NAG7
NTACHDESWCLSOURCE:
MOV CX,RCX1
ROR CX,8
SHR CX,8
ROL CX,8
MOV AX,RCX1
ROR AX,8
SHR AX,8
ADD AX,CX
MOV RCX1,AX
JMP NAG7
NTACHDESWCHSOURCE:
JMP NAG7
NTACHDESWDLSOURCE:
MOV CX,RDX1
ROR CX,8
SHR CX,8
ROL CX,8
MOV AX,RCX1
ROR AX,8
SHR AX,8
ADD AX,CX
MOV RCX1,AX
JMP NAG7
NTACHDESWDHSOURCE:
MOV CX,RDX1
MOV AX,CX
MOV BX,100H
DIV BX
SHL AX,8
MOV CX,AX
MOV AX,RCX1
ROR AX,8
SHR AX,8
ADD AX,CX
MOV RCX1,AX
JMP NAG7
NTACHDESW_RKM_YA_MEMRKM_YAERROR:
MOV AL,[SI+7]
CMP AL,91
JZ MEMRKM_ORERROR_CHDES

RKM_ORERROR_CHDES:
MOV AL,[SI+8]
RET_NUM_COUNT  COMp1+7
CMP CX,2
JA ERROR
MOV AX,RCX1
ROR AX,8
SHR AX,8
SHL DX,8
ADD AX,DX
MOV RCX1,AX
JMP NAG7
MEMRKM_ORERROR_CHDES:
MOV AL,[SI+9]
CMP AL,108
JZ ERROR
CMP AL,104
JZ ERROR

RET_NUM_COUNT  COMp1+8
CMP CX,4
JA ERROR
CMP DX,0FH
JA ERROR
MOV BX,DX
MOV CX,0
MOV CH,MEMORY[BX]
MOV AX,RCX1
ROR AX,8
SHR AX,8
ADD AX,CX
MOV RCX1,AX
JMP NAG7
;//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
NTADHDIS:
  MOV CX,0
  MOV AX,0
  MOV AL,[SI+7] 
  MOV CL,[SI+8]
  ADD AX,CX
  CMP AX,217
  JZ ERROR
  CMP AX,218 
  JZ ERROR
  CMP AX,219
  JZ ERROR
  CMP AX,220
 JZ ERROR
 CMP AX,205
 JZ NTADHDESWDIORALLWDIERROR
 CMP AX,201
 JZ NTADHDESWAHSOURCE
 CMP AX,206
 JZ NTADHDESWBLSOURCE
 CMP AX,202
 JZ NTADHDESWBHSOURCE 
 CMP AX,207
 JZ NTADHDESWCLSOURCE
 CMP AX,203
 JZ NTADHDESWCHSOURCE
 CMP AX,208
 JZ NTADHDESWDLSOURCE
 CMP AX,204
 JZ NTADHDESWDHSOURCE
 MOV BX,0
 MOV CX,0                              ;TAKECARE
 MOV CL,[SI+9]
 MOV BL,[SI+10]
 ADD CX,BX
 ADD AX,CX
 CMP AX,402
 JZ DHDES_WNTA_MEMBX
 CMP AX,404              
 JZ NTA_DHDES_WMEMSI
 CMP AX,389
 JZ NTA_DHDES_WMEMDI
  
 JMP NTADHDESW_RKM_YA_MEMRKM_YAERROR  
 
 
  
NTADHDESWDIORALLWDIERROR: 
MOV AL,[SI+7]
CMP AL,100 
JZ ERROR
NTADHDESWALSOURCE:
MOV CX,RAX1
ROR CX,8
SHR CX,8
ROL CX,8
MOV AX,RDX1
ROR AX,8
SHR AX,8
ADD AX,CX
MOV RDX1,AX
JMP NAG7
DHDES_WNTA_MEMBX:
MOV BX,RBX1
CMP BX,0FH
JA ERROR
MOV CX,0
MOV CH,MEMORY[BX] 
MOV AX,RDX1
ROR AX,8
SHR AX,8
ADD AX,CX              ;MA3 AL CODE W MA3 AH CO
MOV RDX1,AX
JMP NAG7
NTA_DHDES_WMEMSI:
MOV BX,ISI1
CMP BX,0FH
JA ERROR
MOV CX,0
MOV CH,MEMORY[BX] 
MOV AX,RDX1
ROR AX,8
SHR AX,8
ADD AX,CX              ;MA3 AL CODE W MA3 AH CO
MOV RDX1,AX
JMP NAG7
NTA_DHDES_WMEMDI:
MOV BX,IDI1
CMP BX,0FH
JA ERROR
MOV CX,0
MOV CH,MEMORY[BX] 
MOV AX,RDX1
ROR AX,8
SHR AX,8
ADD AX,CX              ;MA3 AL CODE W MA3 AH CO
MOV RDX1,AX
JMP NAG7
NTADHDESWAHSOURCE:
MOV CX,RAX1
MOV AX,CX
MOV BX,100H
DIV BX
SHL AX,8
MOV CX,AX
MOV AX,RDX1
ROR AX,8
SHR AX,8
ADD AX,CX
MOV RDX1,AX
JMP NAG7
NTADHDESWBLSOURCE:
MOV CX,RBX1
ROR CX,8
SHR CX,8
ROL CX,8
MOV AX,RDX1
ROR AX,8
SHR AX,8
ADD AX,CX
MOV RDX1,AX
JMP NAG7
NTADHDESWBHSOURCE:
MOV CX,RBX1
MOV AX,CX
MOV BX,100H
DIV BX
SHL AX,8
MOV CX,AX
MOV AX,RDX1
ROR AX,8
SHR AX,8
ADD AX,CX
MOV RDX1,AX
JMP NAG7
NTADHDESWCLSOURCE:
MOV CX,RCX1
ROR CX,8
SHR CX,8
ROL CX,8
MOV AX,RDX1
ROR AX,8
SHR AX,8
ADD AX,CX
MOV RDX1,AX
JMP NAG7
NTADHDESWCHSOURCE:
MOV CX,RCX1
MOV AX,CX
MOV BX,100H
DIV BX
SHL AX,8
MOV CX,AX
MOV AX,RDX1
ROR AX,8
SHR AX,8
ADD AX,CX
MOV RDX1,AX
JMP NAG7
NTADHDESWDLSOURCE:
MOV CX,RDX1
ROR CX,8
SHR CX,8
ROL CX,8
MOV AX,RDX1
ROR AX,8
SHR AX,8
ADD AX,CX
MOV RDX1,AX
JMP NAG7
NTADHDESWDHSOURCE:
JMP NAG7
NTADHDESW_RKM_YA_MEMRKM_YAERROR:
MOV AL,[SI+7]
CMP AL,91
JZ MEMRKM_ORERROR_DHDES

RKM_ORERROR_DHDES:
MOV AL,[SI+8]
RET_NUM_COUNT  COMp1+7
CMP CX,2
JA ERROR
MOV AX,RDX1
ROR AX,8
SHR AX,8
SHL DX,8
ADD AX,DX
MOV RDX1,AX
JMP NAG7
MEMRKM_ORERROR_DHDES:
MOV AL,[SI+9]
CMP AL,108
JZ ERROR
CMP AL,104
JZ ERROR
RET_NUM_COUNT  COMp1+8
CMP CX,4
JA ERROR
CMP DX,0FH
JA ERROR
MOV BX,DX
MOV CX,0
MOV CH,MEMORY[BX]
MOV AX,RDX1
ROR AX,8
SHR AX,8
ADD AX,CX
MOV RDX1,AX
JMP NAG7
;////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
ERROR:
mov ah,0
mov al,13h
int 10h
PRINT_NUMBER NUM_HEXA,RAX1,NUMTODISP,15,10 
JMP OUTT
NAG7:

OUTT:
finished:
HLT
    MAIN ENDP 
SUB1 proc FAR
    add bl,20h  ;convert upper to lowercase char
    RET
    SUB1 ENDP  
END MAIN
 
  
  
  