.MODEL SMALL
.Data
MESSAGE DB 'MOV AX,ffff','$' 
TEMP DW ?

.CODE  
INCLUDE COUNTNUM.INC
MAIN PROC FAR
    MOV AX,@DATA  
    RET_NUM_COUNT RET_NUM_COUNT+7,TEMP  
  
    
    MAIN ENDP
END MAIN